CenturyLink/Chi

cicd/docker/SonarQube/sonar-project.properties

Sonar Properties were missing an exclusion so it failed

Fixing Sonar Properties

---

cicd/docker/SonarQube/sonar-project.properties

And stopping node_modules exclusion

Removing regression reports from Coverage

---

CHANGELOG.md
package.json
src/boilerplates/angular/chi-angular-boilerplate/src/index.html
src/boilerplates/es6/chi-vue-es6-boilerplate/public/index.html
src/boilerplates/react/chi-react-boilerplate/public/index.html
src/boilerplates/stencil/chi-stencil-boilerplate/src/index.html
src/boilerplates/vue/chi-vue-boilerplate/public/index.html
src/chi-vue/public/index.html
src/custom-elements/docs/docs.json
src/custom-elements/src/index.html
src/website/assets/scripts/globalConfigs.js
src/website/layouts/partials/header.pug
src/website/layouts/partials/sriDoc.pug
src/website/layouts/partials/titlebar.pug
src/website/views/getting-started/whats-new.pug

https://ctl.atlassian.net/browse/FSPE-7449

[FSPE-7449] Prepared 3.13.0 release

---

CHANGELOG.md
package.json
src/boilerplates/angular/chi-angular-boilerplate/src/index.html
src/boilerplates/es6/chi-vue-es6-boilerplate/public/index.html
src/boilerplates/react/chi-react-boilerplate/public/index.html
src/boilerplates/stencil/chi-stencil-boilerplate/src/index.html
src/boilerplates/vue/chi-vue-boilerplate/public/index.html
src/chi-vue/public/index.html
src/custom-elements/docs/docs.json
src/custom-elements/src/index.html
src/website/assets/scripts/globalConfigs.js
src/website/layouts/partials/header.pug
src/website/layouts/partials/sriDoc.pug
src/website/layouts/partials/titlebar.pug
src/website/views/getting-started/whats-new.pug

https://ctl.atlassian.net/browse/FSPE-7669

[FSPE-7669] Prepared release for Chi 3.17.0

---

src/chi-vue/src/components/data-table/DataTable.tsx
src/chi-vue/src/components/pagination/pagination.tsx

@dani-cl-madrid @SergioQCL 
https://ctl.atlassian.net/browse/FSPE-7698

[FSPE-7698] Fixed Chi Vue Data Table single page reactiveness

---

src/website/views/templates/portal.pug

https://ctl.atlassian.net/browse/FSPE-7725

[FSPE-7725] Added portal template for page level actions

---

src/chi/javascript/components/sidenav.js

https://ctl.atlassian.net/browse/FSDE-695

[FSDE-695] Improved removing Sidenav component event listeners

---

src/website/views/components/accordion/_examples.pug

https://ctl.atlassian.net/browse/FSDE-705

[FSDE-705] Updated icon chevron down position in accordion documentation

---

src/chi-vue/src/views/DataTableTemplates/example-popover.vue
src/chi-vue/src/views/DataTableView.vue
src/website/views/components/popover/_examples.pug

https://ctl.atlassian.net/browse/FSDE-699

[FSDE-699] Improved Popover open on hover examples

---

CHANGELOG.md
package.json
src/boilerplates/angular/chi-angular-boilerplate/src/index.html
src/boilerplates/es6/chi-vue-es6-boilerplate/public/index.html
src/boilerplates/react/chi-react-boilerplate/public/index.html
src/boilerplates/stencil/chi-stencil-boilerplate/src/index.html
src/boilerplates/vue/chi-vue-boilerplate/public/index.html
src/custom-elements/docs/docs.json
src/website/assets/scripts/globalConfigs.js
src/website/layouts/partials/header.pug
src/website/layouts/partials/sriDoc.pug
src/website/layouts/partials/titlebar.pug
src/website/views/components/skeleton/_examples.pug
src/website/views/getting-started/whats-new.pug

https://ctl.atlassian.net/browse/FSDE-843

[FSDE-843] Prepared Chi 4.2.0 release

---

src/chi-vue/src/components/data-table/DataTable.tsx
src/chi-vue/src/components/pagination/pagination.tsx

@SergioQCL 
https://ctl.atlassian.net/browse/FSDE-913

[FSDE-913] Fixed Select All checkbox issue

---

cicd/Jenkins/Jenkinsfile

feat: [FSDE-678] Update needed for Topics to be enabled
[FSDE-678]: https://ctl.atlassian.net/browse/FSDE-678

feat: [FSDE-678] Update needed for Topics to be enabled

---

CHANGELOG.md
package.json
src/boilerplates/angular/chi-angular-boilerplate/src/index.html
src/boilerplates/es6/chi-vue-es6-boilerplate/public/index.html
src/boilerplates/react/chi-react-boilerplate/public/index.html
src/boilerplates/stencil/chi-stencil-boilerplate/src/index.html
src/boilerplates/vue/chi-vue-boilerplate/public/index.html
src/custom-elements/docs/docs.json
src/website/assets/scripts/globalConfigs.js
src/website/layouts/partials/header.pug
src/website/layouts/partials/sriDoc.pug
src/website/layouts/partials/titlebar.pug
src/website/views/getting-started/whats-new.pug

https://ctl.atlassian.net/browse/FSDE-963

[FSDE-963] Prepared Chi 4.3.0 release

---

cypress/integration/chi-vue/data-table.spec.js
test/chi/chi-vue/data-table.pug

https://ctl.atlassian.net/browse/FSDE-978

[FSDE-978] Added support of Chi Vue Data Table E2E test template

---

src/chi-vue/src/components/data-table/DataTable.tsx
src/chi-vue/src/constants/classes.ts
src/chi-vue/src/constants/events.ts
src/chi-vue/src/constants/types.ts
src/chi-vue/src/views/DataTableView.vue
src/chi/components/data-table/data-table.scss

@SergioQCL @dani-cl-madrid @aryaroudi @evansito
https://user-images.githubusercontent.com/25136131/123306528-b3ac9080-d521-11eb-88b3-48c3ded148a4.mov

[FSDE-1009][FSDE-1010][FSDE-283] Improved position of nested rows of Data Table

---

CHANGELOG.md
package.json
src/boilerplates/angular/chi-angular-boilerplate/src/index.html
src/boilerplates/es6/chi-vue-es6-boilerplate/public/index.html
src/boilerplates/react/chi-react-boilerplate/public/index.html
src/boilerplates/stencil/chi-stencil-boilerplate/src/index.html
src/boilerplates/vue/chi-vue-boilerplate/public/index.html
src/chi-vue/public/index.html
src/custom-elements/docs/docs.json
src/website/assets/scripts/globalConfigs.js
src/website/layouts/partials/header.pug
src/website/layouts/partials/sriDoc.pug
src/website/layouts/partials/titlebar.pug
src/website/views/getting-started/whats-new.pug

https://ctl.atlassian.net/browse/FSDE-1172

[FSDE-1172] Prepared Chi 4.4.0 release

---

src/chi-vue/package.json
src/chi-vue/src/components/data-table-filters/DataTableFilters.tsx
src/chi-vue/src/components/data-table/DataTable.tsx
src/chi-vue/src/constants/events.ts
src/chi-vue/src/views/DataTable/ServerSide/DataTableServerView.vue
src/custom-elements/docs/docs.json

@dani-cl-madrid @SergioQCL @jllr 
https://ctl.atlassian.net/browse/FSDE-1204

[FSDE-1123] Added support of chiRowSelected and chiRowDeselected events to Chi Vue Data Table component

---

src/website/views/components/drawer/_examples.pug
src/website/views/components/drawer/_properties.pug

[FSDE-1083] Add interactive documentation examples of chi vue drawer

---

src/chi-vue/src/components/tooltip/tooltip.tsx
src/chi-vue/src/constants/types.ts
src/website/views/components/tooltip/_examples.pug
src/website/views/components/tooltip/_properties.pug

[FSDE-1098] Add interactive documentation examples of chi vue tooltip

---

src/boilerplates/vue/chi-vue-boilerplate/.eslintrc.js
src/boilerplates/vue/chi-vue-boilerplate/.npmrc
src/boilerplates/vue/chi-vue-boilerplate/package.json
src/boilerplates/vue/chi-vue-boilerplate/src/components/Header.vue
src/boilerplates/vue/chi-vue-boilerplate/src/main.ts
src/boilerplates/vue/chi-vue-boilerplate/vue.config.js

hey @janibolkvadze @jllr please review this

[FSDE-1174] Update the Chi-Vue boilerplate with new version of CHI-VUE

---

cypress/integration/chi-vue/search-input.spec.js
test/chi/chi-vue/search-input.pug

[FSDE-1140] Add E2E tests to chi-vue search-input component

---

src/website/views/components/footer/_examples.pug

[FSDE-1249] Fix Internal footer links in the HTML Blueprint code

---

CHANGELOG.md
package.json
src/boilerplates/angular/chi-angular-boilerplate/src/index.html
src/boilerplates/es6/chi-vue-es6-boilerplate/public/index.html
src/boilerplates/react/chi-react-boilerplate/public/index.html
src/boilerplates/stencil/chi-stencil-boilerplate/src/index.html
src/boilerplates/vue/chi-vue-boilerplate/public/index.html
src/custom-elements/docs/docs.json
src/website/assets/scripts/globalConfigs.js
src/website/layouts/partials/header.pug
src/website/layouts/partials/sriDoc.pug
src/website/layouts/partials/titlebar.pug
src/website/views/getting-started/whats-new.pug

https://ctl.atlassian.net/browse/FSDE-2133

[FSDE-2133] Prepared Chi 5.1.0 release

---

src/custom-elements/src/components/app-layout/app-layout.tsx

@SergioQCL 
https://ctl.atlassian.net/browse/FSDE-6040

[FSDE-6040] Fixed App layout web component title issue

---

cypress/integration/chi-vue/data-table.spec.js
src/chi-vue/package.json
src/chi-vue/public/index.html
src/chi-vue/src/components/data-table/DataTable.tsx
src/chi-vue/src/components/data-table/DataTableTooltip.tsx
src/chi-vue/src/views/DataTable/ClientSide/fixtures.ts
tasks/build-chi-scripts.js
test/chi/chi-vue/_data-table-base.pug

https://ctl.atlassian.net/browse/FSDE-8524

[FSDE-8524] Added conditional Tooltip to Data Table header cells

---

cicd/Jenkins/Jenkinsfile

This reverts commit 9f2925aeb49f2ab6c605b97ef34ad5a7d602ac63.

Revert "[FSDE-6414] Adding auto prs (#239)"

---

src/chi-vue/src/components/data-table/DataTable.tsx
src/chi-vue/src/components/data-table/default-config.ts
src/chi-vue/src/constants/types.ts
src/chi-vue/src/views/DataTable/ClientSide/fixtures.ts
src/website/views/components/data-table/_properties.pug

https://ctl.atlassian.net/browse/FSDE-16823

[FSDE-16823] Improve printing methods for child and grand child rows in data table

---

src/website/views/components/forms/checkbox/_examples.pug
src/website/views/components/forms/number-input/_examples.pug
src/website/views/components/forms/radio-button/_examples.pug
src/website/views/components/forms/select/_examples.pug
src/website/views/components/forms/text-input/_examples.pug
src/website/views/components/forms/textarea/_examples.pug
src/website/views/components/phone-input/_examples.pug

https://ctl.atlassian.net/browse/FSDE-16767

[FSDE-16767] Added icons to form input error messages

---

Dockerfile
scripts/docker.sh

https://ctl.atlassian.net/browse/FSDE-27024

[FSDE-27024] Fix DevEnv Docker issue of installing dependencies

---

src/custom-elements/src/components/tabs/tabs.tsx

https://ctl.atlassian.net/browse/FSDE-28354

[FSDE-28354] Tabbed navigation - Improve dispose in open dropdowns

---

src/chi/utilities/text.scss

https://ctl.atlassian.net/browse/FSDE-29334

[FSDE-29334] Fix line height prevalence in conjuction with text utility class

---

src/chi-vue/src/components/column-customization/ColumnCustomization.tsx
src/chi-vue/src/components/column-customization/ColumnCustomizationModalContent.tsx
src/chi-vue/src/components/data-table-filters/AdvancedFilters.tsx
src/chi-vue/src/components/data-table-filters/DataTableFilters.tsx
src/chi-vue/src/components/data-table-toolbar/DataTableToolbar.tsx
src/chi-vue/src/components/data-table-views/DataTableViews.tsx
src/chi-vue/src/components/data-table/DataTable.tsx
src/chi-vue/src/components/drawer/drawer.tsx
src/chi-vue/src/components/search-input/SearchInput.tsx
src/chi-vue/src/constants/classes.ts
src/chi-vue/src/utils/utils.ts
src/custom-elements/src/components/tabs/tabs.tsx
src/custom-elements/src/constants/classes.ts

https://ctl.atlassian.net/browse/FSDE-28315

[FSDE-28315] Remove unused variables in Chi vue components

---

cicd/jenkins/Jenkinsfile

https://ctl.atlassian.net/browse/FSDE-29806

[FSDE-29806] Updated CUID in jenkinsfile

---

CHANGELOG.md
package.json
src/boilerplates/angular/chi-angular-boilerplate/src/index.html
src/boilerplates/es6/chi-vue-es6-boilerplate/public/index.html
src/boilerplates/react/chi-react-boilerplate/public/index.html
src/boilerplates/stencil/chi-stencil-boilerplate/src/index.html
src/boilerplates/vue/chi-vue-boilerplate/public/index.html
src/custom-elements/docs/docs.json
src/documentation/constants/configs.ts
src/documentation/constants/constants.ts
src/website/assets/scripts/globalConfigs.js
src/website/layouts/default.pug
src/website/layouts/partials/header.pug
src/website/layouts/partials/sriDoc.pug
src/website/layouts/partials/titlebar.pug
src/website/views/components/toolbar/_examples.pug
src/website/views/getting-started/installation.pug
src/website/views/getting-started/whats-new.pug

https://ctl.atlassian.net/browse/FSDE-29813

[FSDE-29813] Prepared Chi 5.23.0 release

---

src/custom-elements/src/components/tabs/tabs.tsx

https://ctl.atlassian.net/browse/FSDE-29895

[FSDE-29895] Tabbed navigation: Display dropdown menu for child items when included in See more tab

---

src/custom-elements/src/components/tabs/tabs.tsx

https://ctl.atlassian.net/browse/FSDE-30021

[FSDE-30021] Tabed navigation: Fix See more dropdown function console error

---

CHANGELOG.md
package.json
src/boilerplates/angular/chi-angular-boilerplate/src/index.html
src/boilerplates/es6/chi-vue-es6-boilerplate/public/index.html
src/boilerplates/react/chi-react-boilerplate/public/index.html
src/boilerplates/stencil/chi-stencil-boilerplate/src/index.html
src/boilerplates/vue/chi-vue-boilerplate/public/index.html
src/custom-elements/docs/docs.json
src/documentation/constants/configs.ts
src/documentation/constants/constants.ts
src/website/assets/scripts/globalConfigs.js
src/website/layouts/default.pug
src/website/layouts/partials/header.pug
src/website/layouts/partials/sriDoc.pug
src/website/layouts/partials/titlebar.pug
src/website/views/getting-started/installation.pug
src/website/views/getting-started/whats-new.pug

https://ctl.atlassian.net/browse/FSDE-30231

[FSDE-30231] Prepared Chi 5.25.0 release

---

LICENSE
src/boilerplates/stencil/chi-stencil-boilerplate/LICENSE
src/custom-elements/LICENSE

https://ctl.atlassian.net/browse/FSDE-30326

[FSDE-30326] Updated license copyright year

---

CHANGELOG.md
package.json
src/boilerplates/angular/chi-angular-boilerplate/src/index.html
src/boilerplates/es6/chi-vue-es6-boilerplate/public/index.html
src/boilerplates/react/chi-react-boilerplate/public/index.html
src/boilerplates/stencil/chi-stencil-boilerplate/src/index.html
src/boilerplates/vue/chi-vue-boilerplate/public/index.html
src/custom-elements/docs/docs.json
src/documentation/constants/configs.ts
src/documentation/constants/constants.ts
src/website/assets/scripts/globalConfigs.js
src/website/layouts/default.pug
src/website/layouts/partials/header.pug
src/website/layouts/partials/sriDoc.pug
src/website/layouts/partials/titlebar.pug
src/website/views/getting-started/installation.pug
src/website/views/getting-started/whats-new.pug

https://ctl.atlassian.net/browse/FSDE-30417

[FSDE-30417] Prepare Chi 5.26.0 release

---

src/documentation/nuxt.config.js
src/documentation/package-lock.json
src/documentation/package.json

https://ctl.atlassian.net/browse/FSDE-30454

[FSDE-30454] Fix Chi documentation dependencies

---

src/chi-vue/src/components/data-table/DataTable.tsx

https://ctl.atlassian.net/browse/FSDE-30509

[FSDE-30509] Add support of sorting when no dates is defined in data table

---

src/custom-elements/src/components/number-input/number-input.tsx
src/website/views/components/forms/number-input/_examples.pug

https://ctl.atlassian.net/browse/FSDE-30590

[FSDE-30590] Fix number input min/max/step example

---

CHANGELOG.md
package.json
src/boilerplates/angular/chi-angular-boilerplate/src/index.html
src/boilerplates/es6/chi-vue-es6-boilerplate/public/index.html
src/boilerplates/react/chi-react-boilerplate/public/index.html
src/boilerplates/stencil/chi-stencil-boilerplate/src/index.html
src/boilerplates/vue/chi-vue-boilerplate/public/index.html
src/chi-vue/public/index.html
src/documentation/constants/configs.ts
src/documentation/constants/constants.ts
src/website/assets/scripts/globalConfigs.js
src/website/layouts/default.pug
src/website/layouts/partials/header.pug
src/website/layouts/partials/sriDoc.pug
src/website/layouts/partials/titlebar.pug
src/website/views/getting-started/installation.pug
src/website/views/getting-started/whats-new.pug

https://ctl.atlassian.net/browse/FSDE-30591

[FSDE-30591] Prepared Chi 5.27.0 release

---

src/website/views/components/toolbar/_properties.pug

add documentation for toolbar SaveView

[FSDE-30479] Add Save view Vue properties

---

src/custom-elements/package-lock.json
src/custom-elements/tsconfig.json

https://ctl.atlassian.net/browse/FSDE-30679

[FSDE-30679] Fix Chi Web components dependencies

---

src/chi-vue/src/components/data-table/DataTable.tsx
src/chi-vue/src/components/data-table/default-config.ts
src/chi-vue/src/constants/types.ts
src/website/views/components/data-table/_properties.pug

Add config for allowing expand/collapse all functionality in data table

[FSDE-30678] Add prop showExpandAll to expand/collapse all functionality in data table

---

src/chi-vue/src/components/data-table/DataTable.tsx

https://ctl.atlassian.net/browse/FSDE-30681

[FSDE-30681] Improve order update of cells in data table

---

src/chi-vue/package-lock.json
src/chi-vue/package.json
src/chi-vue/src/components/column-customization/ColumnCustomizationModalContent.tsx
src/chi-vue/src/components/data-table-filters/AdvancedFilters.tsx
src/chi-vue/src/components/data-table-filters/DataTableFilters.tsx
src/chi-vue/src/components/pagination/pagination.tsx

https://ctl.atlassian.net/browse/FSDE-30696

[FSDE-30696] Fix Chi Vue types dependencies

---

src/chi-vue/src/components/data-table/DataTable.tsx

https://ctl.atlassian.net/browse/FSDE-30697

[FSDE-30697] Fix showExpandAll prop config when set to false

---

src/chi-vue/package-lock.json
src/chi-vue/package.json
src/chi-vue/src/components/data-table/DataTable.tsx
src/chi-vue/src/views/DataTable/ClientSide/DataTableClientView.vue
src/chi-vue/src/views/DataTable/ServerSide/DataTableServerView.vue

https://ctl.atlassian.net/browse/FSDE-30686

[FSDE-30686] Fix select all and deselect all errros when loaded dinamically

---

src/custom-elements/src/components/carousel/carousel.tsx
src/custom-elements/src/constants/classes.ts

https://ctl.atlassian.net/browse/FSDE-30485

[FSDE-30485] Add chi-stat__item condition in carousel 

---

src/chi-vue/src/components/data-table/DataTable.tsx
src/website/views/components/data-table/_properties.pug

https://ctl.atlassian.net/browse/FSDE-30715

[FSDE-30715] Include showSelectAllDropdown config in documentation

---

src/chi-vue/package-lock.json
src/chi-vue/package.json

https://ctl.atlassian.net/browse/FSDE-30751

[FSDE-30751] Fixed Vue to 2.6.14 in Chi Vue

---

.github/dependabot.yml
src/chi-vue/package-lock.json
src/chi-vue/package.json
src/chi-vue/vue.config.js
src/documentation/package-lock.json
src/documentation/package.json

https://ctl.atlassian.net/browse/FSDE-30780

[FSDE-30780] Fix Chi Vue export webpack dependencies

---

src/chi-vue/src/components/data-table/default-config.ts
src/chi-vue/src/views/DataTable/ClientSide/fixtures.ts
src/chi-vue/src/views/DataTable/ServerSide/fixtures.ts
src/website/views/components/data-table/examples/base/_accordion.pug
src/website/views/components/data-table/examples/base/_selectable.pug
src/website/views/components/data-table/examples/portal/_accordion-child.pug
src/website/views/components/data-table/examples/portal/_accordion-grand-child.pug
src/website/views/components/data-table/examples/portal/_accordion.pug
src/website/views/components/data-table/examples/portal/_complex.pug

https://ctl.atlassian.net/browse/FSDE-30773

[FSDE-30773] Change showExpandAll and showSelectedAllDropdown config to false by default

---

src/website/views/getting-started/browsers-devices.pug

https://ctl.atlassian.net/browse/FSDE-30896

[FSDE-30896] Remove ie11 support in Browser support page

---

src/website/views/components/data-table/_examples.pug
src/website/views/components/data-table/examples/portal/_radio-selection.pug

https://ctl.atlassian.net/browse/FSDE-30880
- Created a new component for radio selection in the Portal's directory base
- Component implemented in examples

[FSDE-30880] Implement datatable radio selection component to be used in Lumen Enterprise Portal

---

CHANGELOG.md
package.json
src/boilerplates/angular/chi-angular-boilerplate/src/index.html
src/boilerplates/es6/chi-vue-es6-boilerplate/public/index.html
src/boilerplates/react/chi-react-boilerplate/public/index.html
src/boilerplates/stencil/chi-stencil-boilerplate/src/index.html
src/boilerplates/vue/chi-vue-boilerplate/public/index.html
src/chi-vue/package.json
src/chi-vue/public/index.html
src/custom-elements/docs/docs.json
src/documentation/constants/configs.ts
src/documentation/constants/constants.ts
src/website/assets/scripts/globalConfigs.js
src/website/layouts/default.pug
src/website/layouts/partials/header.pug
src/website/layouts/partials/sriDoc.pug
src/website/layouts/partials/titlebar.pug
src/website/views/components/data-table/examples/portal/_two-tier.pug
src/website/views/components/tabs/_examples.pug
src/website/views/getting-started/installation.pug
src/website/views/getting-started/whats-new.pug

https://ctl.atlassian.net/browse/FSDE-30921

[FSDE-30921] Prepared Chi 5.29.0 release

---

src/chi-vue/src/components/expansion-panel/ExpansionPanel.tsx
src/chi-vue/src/constants/classes.ts

https://ctl.atlassian.net/browse/FSDE-31041

[FSDE-31041] Add stateIcon property to expansion panel Vue component

---

src/chi/utilities/text.scss
src/website/views/utilities/text.pug

https://ctl.atlassian.net/browse/FSDE-31157

[FSDE-31157] Added capitalize first letter text utility

---

src/chi-vue/src/components/column-customization/ColumnCustomization.tsx
src/chi-vue/src/views/DataTable/ClientSide/DataTableClientView.vue
src/documentation/pages/components-wip/toolbar/_examples/_base-with-save-view.vue
src/documentation/pages/components-wip/toolbar/_examples/_base.vue
src/documentation/pages/components-wip/toolbar/_examples/_portal/_base-with-save-view-bulk-actions.vue
src/website/views/components/toolbar/_examples.pug

https://ctl.atlassian.net/browse/FSDE-31237

[FSDE-31237] Change Column customization tooltip text to Customize Columns

---

src/documentation/pages/utilities-wip/overflow/examples/_auto.vue
src/documentation/pages/utilities-wip/overflow/examples/_hidden.vue
src/documentation/pages/utilities-wip/overflow/examples/index.vue
src/documentation/pages/utilities-wip/overflow/index.vue

https://ctl.atlassian.net/browse/FSDE-18261

[FSDE-18261] Migrate overflow utility

---

src/chi-vue/.eslintrc.js
src/chi-vue/package-lock.json
src/chi-vue/src/build/vue-wrapper.ts
src/chi-vue/src/components/column-customization/AvailableColumns.tsx
src/chi-vue/src/components/column-customization/ColumnCustomization.tsx
src/chi-vue/src/components/column-customization/ColumnCustomizationModalContent.tsx
src/chi-vue/src/components/column-customization/SelectedColumns.tsx
src/chi-vue/src/components/data-table-filters/DataTableFilters.tsx
src/chi-vue/src/components/data-table-save-view/SaveView.tsx
src/chi-vue/src/components/data-table-views/DataTableViews.tsx
src/chi-vue/src/components/drawer/drawer.tsx
src/chi-vue/src/components/pagination/pagination.tsx
src/chi-vue/src/components/search-input/SearchInput.tsx
src/chi-vue/src/components/tooltip/tooltip.tsx

https://ctl.atlassian.net/browse/FSDE-31436

[FSDE-31436] Fix Chi Vue wrapper building

---

src/chi-vue/src/components/expansion-panel/expansion-panel.scss

https://ctl.atlassian.net/browse/FSDE-31464

[FSDE-31464] Fixed Chi Vue expansion panel alignment when state icon is present

---

src/chi-vue/src/components/expansion-panel/ExpansionPanel.tsx

https://ctl.atlassian.net/browse/FSDE-31462

[FSDE-31462] Fix done state in Chi vue expansion panel

---

cypress/integration/chi-custom-elements/search-input.spec.js
test/chi/custom-elements/search-input.pug

https://ctl.atlassian.net/browse/FSDE-31405

[FSDE-31405] create e2e tests to autocomplete mode

---

src/documentation/package-lock.json
src/documentation/package.json

https://ctl.atlassian.net/browse/FSDE-31522

[FSDE-31522] Fix new Vue doc dependencies

---

src/website/views/components/forms/text-input/_examples.pug

https://ctl.atlassian.net/browse/FSDE-31609

[FSDE-31609] Add helper message to text input web component documentation

---

src/website/views/components/data-table/examples/base/_complex.pug

https://ctl.atlassian.net/browse/FSDE-31655

[FSDE-31655] Add icon example in data table header complex example

---

package.json
src/boilerplates/angular/chi-angular-boilerplate/src/index.html
src/boilerplates/es6/chi-vue-es6-boilerplate/public/index.html
src/boilerplates/react/chi-react-boilerplate/public/index.html
src/boilerplates/stencil/chi-stencil-boilerplate/src/index.html
src/boilerplates/vue/chi-vue-boilerplate/public/index.html
src/chi-vue/package-lock.json
src/chi-vue/package.json
src/chi-vue/public/index.html
src/documentation/package-lock.json
src/documentation/package.json
src/website/views/components/table/_examples.pug
src/website/views/components/table/index.pug

https://ctl.atlassian.net/browse/FSDE-31750

[FSDE-31750] Fix node dependency in Jenkins pipeline

---

src/website/views/components/data-table/examples/portal/_complex.pug

https://ctl.atlassian.net/browse/FSDE-31698

[FSDE-31698] Fix data table complex example in Portal theme

---

cypress/integration/chi-custom-elements/text-input.spec.js

https://ctl.atlassian.net/browse/FSDE-31608

[FSDE-31608] Implement some functional use case tests for helper message in text input component

---

src/website/views/components/forms/toggle-switch/_examples.pug

https://ctl.atlassian.net/browse/DPEDE-370

[DPEDE-370] Changed toggle switch xs size to sm in Portal

---

cicd/docker/SonarQube/sonar-project.properties

https://ctl.atlassian.net/browse/DPEDE-599

[DPEDE-599] Excluded new vue doc in sonar properties

---

src/documentation/pages/foundations-wip/accessibility/tables/examples/_info-and-relationships.vue
src/documentation/pages/foundations-wip/accessibility/tables/examples/index.vue
src/documentation/pages/foundations-wip/accessibility/tables/index.vue

https://ctl.atlassian.net/jira/software/c/projects/DPEDE/boards/7135?modal=detail&selectedIssue=DPEDE-544

[DPEDE-544] Migrate foundations accessibility tables to new Vue documentation

---

src/chi-vue/src/components/column-customization/ColumnCustomization.tsx

https://ctl.atlassian.net/browse/DPEDE-592

[DPEDE-592] Fix column customization unexpected behavior detected when cancelling

---

cypress/e2e/chi-custom-elements/carousel.cy.js
src/custom-elements/src/components/carousel/carousel.tsx

https://ctl.atlassian.net/browse/DPEDE-647

[DPEDE-647] Fix stat item active state

---

src/custom-elements/docs/docs.json
src/website/views/components/modal/_examples.pug

https://ctl.atlassian.net/browse/DPEDE-708

[DPEDE-708] Centered single action button in Modals

---

.github/dependabot.yml
src/documentation/package-lock.json
src/documentation/package.json

https://ctl.atlassian.net/browse/DPEDE-819

[DPEDE-819] Fix new Vue documentation dependencies

---

src/chi/components/dropdown/dropdown.scss
src/website/views/components/dropdown/_examples.pug

https://ctl.atlassian.net/browse/DPEDE-878

[DPEDE-878] Create dropdown example with search input in dropdown menu

---

src/boilerplates/angular/chi-angular-boilerplate/src/index.html
src/boilerplates/es6/chi-vue-es6-boilerplate/public/index.html
src/boilerplates/react/chi-react-boilerplate/public/index.html
src/boilerplates/stencil/chi-stencil-boilerplate/src/index.html
src/boilerplates/vue/chi-vue-boilerplate/public/index.html
src/website/views/components/progress/_examples.pug

https://ctl.atlassian.net/browse/DPEDE-915

[DPEDE-915] Added modal progress bar example in doc

---

src/documentation/pages/getting-started-wip/installation/examples/_javascript.vue
src/website/views/getting-started/installation.pug

https://ctl.atlassian.net/browse/DPEDE-967

[DPEDE-967] Deleted ES6 tab from javascript installation page

---

src/documentation/constants/constants.ts
src/documentation/nuxt.config.js
src/documentation/package-lock.json
src/documentation/package.json
src/documentation/plugins/chi-docs.js

https://ctl.atlassian.net/browse/DPEDE-969

[DPEDE-969] Improve doc urls depending on env

---

src/website/views/components/data-table/_examples.pug
src/website/views/components/forms/search-input/_examples.pug
src/website/views/components/toolbar/_examples.pug
src/website/views/getting-started/installation.pug

https://ctl.atlassian.net/browse/DPEDE-1181

[DPEDE-1181] Fix Vue examples in Chi 5.44 version

---

cicd/jenkins/Jenkinsfile

https://ctl.atlassian.net/browse/DPEDE-1180

[DPEDE-1180] Improve CICD Jenkins pipeline

---

.github/dependabot.yml
cypress/e2e/chi-custom-elements/alert.cy.js
src/custom-elements/package-lock.json
src/custom-elements/package.json
src/custom-elements/src/components/alert/alert.tsx
src/custom-elements/src/index.html
src/custom-elements/src/utils/mutationObserver.ts
src/custom-elements/stencil.config.ts
src/documentation/package-lock.json
test/chi/custom-elements/alert-toast.pug

https://ctl.atlassian.net/browse/DPEDE-1179

[DPEDE-1179] Reusable mutationObserver and implementation in chi-alert

---

src/website/views/components/data-table/examples/portal/_complex.pug

Make poper id unique for portal

[DPEDE-1212] Fix Datatable name popover for Portal

---

cypress/e2e/chi-vue/data-table/client-side/data-table.cy.js
cypress/e2e/chi-vue/data-table/data-table-common.cy.js
src/chi-vue/package-lock.json
src/chi-vue/src/components/data-table/DataTable.tsx
src/chi-vue/src/constants/types.ts
src/chi-vue/src/views/DataTable/ClientSide/fixtures.ts
src/website/views/components/data-table/_properties.pug
test/chi/chi-vue/_data-table-base.pug

https://ctl.atlassian.net/browse/DPEDE-1213

[DPEDE-1213] Add tooltip support in DataTable disabled checkboxes and radio button

---

src/chi-vue/package-lock.json
src/chi-vue/package.json
src/chi-vue/src/components/checkbox/Checkbox.tsx
src/custom-elements/package-lock.json
src/custom-elements/package.json
src/documentation/package-lock.json
src/documentation/package.json

https://ctl.atlassian.net/browse/DPEDE-1231

[DPEDE-1231] Fix select all functionality in data table

---

cicd/jenkins/Jenkinsfile
src/chi-vue/package-lock.json
src/chi-vue/package.json

https://ctl.atlassian.net/browse/DPEDE-1358

[DPEDE-1358] Fix installation of Chi Vue dependencies in Jenkins

---

src/documentation/utilities/utilities.ts

https://ctl.atlassian.net/browse/DPEDE-1282
Adjusted code in generateContent function

[DPEDE-1282] Text Utilities Fix for code display

---

src/custom-elements/src/components/textarea/textarea.tsx

https://ctl.atlassian.net/browse/DPEDE-1328

[DPEDE-1328] Add mutation observer to textarea web component

---

cypress/e2e/chi-custom-elements/date-picker.cy.js
test/chi/custom-elements/date-picker.pug

Maybe it's too much but I've created 3 different tests relying on the value of the attribute (minutesStep). Maybe one test it's enough. Up to you.
Tests:
- minutesStep = 5
- minutesStep = 30
- No value (default = 15)

[DPEDE-1297] Add functional tests for new minutes step property in Date Picker

---

cypress/e2e/chi-custom-elements/tabs.cy.js
src/custom-elements/src/components/tabs/tabs.tsx
test/chi/custom-elements/tabs.pug

https://ctl.atlassian.net/browse/DPEDE-1348
- Fixed tabbed navigation
- Improved logic to fit the last tab without accounting for the "see more tab"

[DPEDE-1348] Fix tabbed navigation

---

src/custom-elements/src/components/helper-message/helper-message.tsx

https://ctl.atlassian.net/browse/DPEDE-1332

[DPEDE-1332] Add mutation observer to helper message web component

---

src/chi-vue/src/components/data-table/DataTable.tsx
src/chi-vue/src/constants/events.ts
src/chi-vue/src/views/DataTable/ClientSide/DataTableClientView.vue
src/chi-vue/src/views/DataTable/ServerSide/DataTableServerView.vue

https://ctl.atlassian.net/browse/DPEDE-1400

[DPEDE-1400] Add chiRowClick event in data table

---

src/custom-elements/src/components/link/link.tsx

[https://ctl.atlassian.net/browse/DPEDE-1329](https://ctl.atlassian.net/browse/DPEDE-1329)

[DPEDE-1329] Add mutation observer to link web component

---

src/custom-elements/src/components/marketing-icon/marketing-icon.tsx

[https://ctl.atlassian.net/browse/DPEDE-1411](https://ctl.atlassian.net/browse/DPEDE-1411)

[DPEDE-1411] Add mutation observer to Marketing Icon web component

---

CHANGELOG.md
package.json
src/boilerplates/stencil/chi-stencil-boilerplate/src/index.html
src/chi-vue/index.html
src/chi-vue/package-lock.json
src/chi-vue/src/build/plugin/constants.ts
src/custom-elements/docs/docs.json
src/custom-elements/src/index.html
src/documentation/constants/configs.ts
src/documentation/constants/constants.ts
src/website/assets/scripts/globalConfigs.js
src/website/layouts/default.pug
src/website/layouts/partials/header.pug
src/website/layouts/partials/sriDoc.pug
src/website/layouts/partials/titlebar.pug
src/website/views/getting-started/installation.pug
src/website/views/getting-started/whats-new.pug

https://ctl.atlassian.net/browse/DPEDE-1457

[DPEDE-1457] Prepare Chi 5.51.1 release

---

cypress/e2e/chi-custom-elements/tabs.cy.js
src/custom-elements/src/components/tabs/tabs.tsx
src/custom-elements/src/constants/types.ts
test/chi/custom-elements/tabs.pug

https://ctl.atlassian.net/browse/DPEDE-1439

[DPEDE-1439] Add visible items attribute/property to dropdowns in tabbed navigation bar component

---

src/chi/components/dropdown/dropdown.scss
src/documentation/pages/components-wip/dropdown/examples/_icons.vue
src/website/views/components/dropdown/_examples.pug

[DPEDE-1468] Added dropdown -icon--right class with documentation

---

src/documentation/pages/components-wip/data-table/_properties.vue
src/documentation/pages/components-wip/data-table/examples/base/_accordion.vue
src/documentation/pages/components-wip/data-table/examples/base/_active.vue
src/documentation/pages/components-wip/data-table/examples/base/_base.vue
src/documentation/pages/components-wip/data-table/examples/base/_complex.vue
src/documentation/pages/components-wip/data-table/examples/base/_config-styled.vue
src/documentation/pages/components-wip/data-table/examples/base/_empty.vue
src/documentation/pages/components-wip/data-table/examples/base/_selectable.vue
src/documentation/pages/components-wip/data-table/examples/base/_sizes.vue
src/documentation/pages/components-wip/data-table/examples/base/_sorting.vue
src/documentation/pages/components-wip/data-table/examples/dropdown-example.vue
src/documentation/pages/components-wip/data-table/examples/index.vue
src/documentation/pages/components-wip/data-table/examples/popover-example.vue
src/documentation/pages/components-wip/data-table/examples/portal/_accordion.vue
src/documentation/pages/components-wip/data-table/examples/portal/_base.vue
src/documentation/pages/components-wip/data-table/examples/portal/_complex.vue
src/documentation/pages/components-wip/data-table/examples/portal/_empty.vue
src/documentation/pages/components-wip/data-table/examples/portal/_radio-selection.vue
src/documentation/pages/components-wip/data-table/examples/portal/_second-line-wrapping.vue
src/documentation/pages/components-wip/data-table/examples/portal/_state.vue
src/documentation/pages/components-wip/data-table/examples/portal/_two-tier.vue
src/website/views/components/data-table/_properties.pug
src/website/views/components/data-table/examples/base/_radio-selection.pug
src/website/views/components/data-table/examples/portal/_radio-selection.pug
src/website/views/components/data-table/examples/portal/_two-tier.pug

https://ctl.atlassian.net/browse/DPEDE-1518
Update examples in documentation for data-table.
Adds missing documentation for `chiRowClick` event.

[DPEDE-1518] Review all examples of data table in documentation

---

src/documentation/pages/foundations-wip/accessibility/overview/examples/_descriptions.vue
src/documentation/pages/foundations-wip/accessibility/overview/examples/_foundations.vue
src/website/views/foundations/accessibility/overview.pug

https://ctl.atlassian.net/browse/DPEDE-1616

[DPEDE-1616] Update accessibility overview page to wcag 2.2

---

src/documentation/pages/foundations-wip/accessibility/page-structure/examples/_bypass_blocks.vue
src/documentation/pages/foundations-wip/accessibility/page-structure/examples/_consistant-identification.vue
src/documentation/pages/foundations-wip/accessibility/page-structure/examples/_consistant-navigation.vue
src/documentation/pages/foundations-wip/accessibility/page-structure/examples/_heading-labels.vue
src/documentation/pages/foundations-wip/accessibility/page-structure/examples/_language-page.vue
src/documentation/pages/foundations-wip/accessibility/page-structure/examples/_language-parts.vue
src/documentation/pages/foundations-wip/accessibility/page-structure/examples/_link-purpose.vue
src/documentation/pages/foundations-wip/accessibility/page-structure/examples/_meaningful-sequence.vue
src/documentation/pages/foundations-wip/accessibility/page-structure/examples/_multiple-ways.vue
src/documentation/pages/foundations-wip/accessibility/page-structure/examples/_page-titled.vue
src/documentation/pages/foundations-wip/accessibility/page-structure/examples/_parsing.vue
src/website/views/foundations/accessibility/page-structure.pug

https://ctl.atlassian.net/browse/DPEDE-1618

[DPEDE-1618] Update accessibility page structure page to WCAG 2.2

---

src/documentation/pages/components-wip/forms/toggle-switch/_accessibility.vue
src/documentation/pages/foundations-wip/accessibility/using-keyboard/examples/_focus-order.vue
src/documentation/pages/foundations-wip/accessibility/using-keyboard/examples/_focus-visible.vue
src/documentation/pages/foundations-wip/accessibility/using-keyboard/examples/_info-and-relationships.vue
src/documentation/pages/foundations-wip/accessibility/using-keyboard/examples/_keyboard.vue
src/documentation/pages/foundations-wip/accessibility/using-keyboard/examples/_no-keyboard.vue
src/website/views/components/forms/toggle-switch/_accessibility.pug
src/website/views/foundations/accessibility/using-keyboard.pug

https://ctl.atlassian.net/browse/DPEDE-1612

[DPEDE-1612] Create accessibility page for toggle switch

---

cypress/e2e/chi-custom-elements/date-picker.cy.js
src/custom-elements/src/components/date-picker/date-picker.tsx
test/chi/custom-elements/date-picker.pug

- addded tests for out of range input date in datetime mode (with time)
- refactored the code so it looks cleaner and prevent adding 'undefined' as time when time is not passed

[DPEDE-1763] Added tests for datepicker out of range input in datetime mode

---

src/chi-vue/package-lock.json
src/chi-vue/package.json
src/custom-elements/package-lock.json
src/custom-elements/package.json
src/documentation/package-lock.json
src/documentation/package.json

https://ctl.atlassian.net/browse/DPEDE-1784

[DPEDE-1784] Fix Chi dependencies

---

src/documentation/pages/components-wip/date-picker/_accessibility.vue
src/website/views/components/date-picker/_accessibility.pug

https://ctl.atlassian.net/browse/DPEDE-1614

[DPEDE-1614] Create accessibility page for date picker

---

src/chi-vue/src/App.vue
src/chi-vue/src/views/DataTableModalView.vue

https://ctl.atlassian.net/browse/DPEDE-1820

[DPEDE-1820] Create data table inside modal example

---

src/chi-vue/package-lock.json
src/chi-vue/package.json
src/documentation/pages/components-wip/dropdown/examples/_select_mode.vue
src/documentation/pages/components-wip/dropdown/examples/index.vue
src/website/views/components/dropdown/_examples.pug

https://ctl.atlassian.net/browse/DPEDE-1726

[DPEDE-1726] Add dropdown select mode examples to documentation

---

src/chi-vue/package-lock.json
src/chi-vue/package.json

https://ctl.atlassian.net/browse/DPEDE-1883

[DPEDE-1883] Prepare Chi Vue 3.5.0 release

---

CHANGELOG.md
package.json
src/chi-vue/index.html
src/chi-vue/package-lock.json
src/chi-vue/src/build/plugin/constants.ts
src/custom-elements/docs/docs.json
src/custom-elements/package-lock.json
src/custom-elements/src/index.html
src/documentation/constants/configs.ts
src/documentation/constants/constants.ts
src/website/assets/scripts/globalConfigs.js
src/website/layouts/default.pug
src/website/layouts/partials/header.pug
src/website/layouts/partials/sriDoc.pug
src/website/layouts/partials/titlebar.pug
src/website/views/components/button/_accessibility.pug
src/website/views/components/date-picker/_accessibility.pug
src/website/views/components/forms/checkbox/_accessibility.pug
src/website/views/components/forms/radio-button/_accessibility.pug
src/website/views/components/forms/select/_accessibility.pug
src/website/views/components/forms/text-input/_accessibility.pug
src/website/views/components/forms/textarea/_accessibility.pug
src/website/views/components/forms/toggle-switch/_accessibility.pug
src/website/views/components/link/_accessibility.pug
src/website/views/components/phone-input/_accessibility.pug
src/website/views/components/time-picker/_accessibility.pug
src/website/views/getting-started/installation.pug
src/website/views/getting-started/whats-new.pug

https://ctl.atlassian.net/browse/DPEDE-1996

[DPEDE-1996] Prepare Chi 5.69.0 release

---

.github/dependabot.yml
src/boilerplates/stencil/chi-stencil-boilerplate/src/index.html
src/chi-vue/README.md
src/chi-vue/package-lock.json
src/chi-vue/package.json
src/custom-elements/package-lock.json
src/custom-elements/package.json
src/documentation/package-lock.json
src/documentation/package.json
src/website/views/getting-started/installation.pug

https://ctl.atlassian.net/browse/DPEDE-2006

[DPEDE-2006] Prepare Chi Vue 3.6.0 release

---

src/documentation/package-lock.json
src/documentation/pages/components/transfer-list/_properties.vue
src/documentation/pages/components/transfer-list/examples/_modal-config.vue
src/documentation/pages/components/transfer-list/examples/_modal.vue
src/documentation/pages/components/transfer-list/examples/index.vue

https://ctl.atlassian.net/browse/DPEDE-1641

[DPEDE-1641] Add transfer list modal mode to doc

---

src/custom-elements/src/components/tabs/tabs.tsx

https://ctl.atlassian.net/browse/DPEDE-2066

[DPEDE-2066] Improve tabbed navigation function

---

cypress/e2e/chi-vue/transfer-list.cy.js
test/chi/chi-vue/transfer-list.pug

https://ctl.atlassian.net/browse/DPEDE-1546

[DPEDE-1546] Create transfer list e2e tests

---

src/chi-vue/src/components/data-table-save-view/SaveView.tsx

https://ctl.atlassian.net/browse/DPEDE-2108

[DPEDE-2108] Improve Save view updated dynamic configuration

---

cypress/e2e/chi-custom-elements/dropdown.cy.js
cypress/e2e/chi-custom-elements/search-input.cy.js
src/custom-elements/src/components/dropdown/dropdown.tsx
src/custom-elements/src/components/search-input/search-input.tsx

https://ctl.atlassian.net/browse/DPEDE-1978

[DPEDE-1978] Fix search input autocomplete active item

---

cypress/e2e/chi-custom-elements/tabs.cy.js
src/custom-elements/src/components/tabs/tabs.tsx
test/chi/custom-elements/tabs.pug

https://ctl.atlassian.net/browse/DPEDE-2026

[DPEDE-2026] Fix console error when active tab is not set

---

cicd/docker/SonarQube/sonar-project.properties
src/documentation/components/DocumentationLinkList.vue
src/documentation/components/Header.vue
src/documentation/components/Navigation.vue
src/documentation/components/ThemeSwitcher.vue
src/website/assets/scripts/chi-docs.js

https://ctl.atlassian.net/browse/DPEDE-1976
- Adds theme to route params to all sidenav links
Can be tested by:
- Change theme in any of the exposed pages (vue)
- Go to any page not exposed (website/..), check that the theme is the selected before
- Change theme
- Go to any exposed pages, check that theme is the selected before

[DPEDE-1976] Add route params to docs vue to keep theme

---

cypress/e2e/chi-vue/data-table/client-side/data-table.cy.js
cypress/e2e/chi-vue/data-table/data-table-sorting.cy.js
cypress/e2e/chi-vue/data-table/server-side/data-table-portal.cy.js
cypress/e2e/chi-vue/data-table/server-side/data-table.cy.js
src/chi-vue/src/components/column-customization/column-customization.scss
src/chi-vue/src/components/data-table-save-view/SaveView.tsx
src/chi-vue/src/components/data-table/DataTable.tsx
src/custom-elements/docs/docs.json
test/chi/chi-vue/_data-table-sorting.pug
test/chi/chi-vue/data-table.pug

https://ctl.atlassian.net/browse/DPEDE-2109
- Watch config to re-sort data if `defaultSort` has changed
- Render correct icon on first render for server side with `fullServerSort` configuration

[DPEDE-2109] Default sort data table

---

src/documentation/components/ThemeSwitcher.vue
src/documentation/constants/scripts.ts
src/documentation/pages/components/forms/file-input/examples/_sizes.vue

https://ctl.atlassian.net/browse/DPEDE-2190

[DPEDE-2190] Fix redirect in vue docs from footer page

---

CHANGELOG.md
package.json
src/boilerplates/stencil/chi-stencil-boilerplate/src/index.html
src/chi-vue/index.html
src/chi-vue/package-lock.json
src/chi-vue/src/build/plugin/constants.ts
src/custom-elements/docs/docs.json
src/custom-elements/package-lock.json
src/documentation/constants/configs.ts
src/documentation/constants/constants.ts
src/website/assets/scripts/globalConfigs.js
src/website/layouts/default.pug
src/website/layouts/partials/header.pug
src/website/layouts/partials/sriDoc.pug
src/website/layouts/partials/titlebar.pug
src/website/views/components/button/_accessibility.pug
src/website/views/components/date-picker/_accessibility.pug
src/website/views/components/forms/checkbox/_accessibility.pug
src/website/views/components/forms/number-input/_accessibility.pug
src/website/views/components/forms/radio-button/_accessibility.pug
src/website/views/components/forms/select/_accessibility.pug
src/website/views/components/forms/text-input/_accessibility.pug
src/website/views/components/forms/textarea/_accessibility.pug
src/website/views/components/forms/toggle-switch/_accessibility.pug
src/website/views/components/link/_accessibility.pug
src/website/views/components/phone-input/_accessibility.pug
src/website/views/components/picker-group/_accessibility.pug
src/website/views/components/time-picker/_accessibility.pug
src/website/views/getting-started/installation.pug
src/website/views/getting-started/whats-new.pug

https://ctl.atlassian.net/browse/DPEDE-2105

[DPEDE-2105] Prepare Chi 5.76.0 release

---

src/documentation/pages/components-wip/picker/_accessibility.vue
src/website/views/components/picker/_accessibility.pug

https://ctl.atlassian.net/browse/DPEDE-2089

[DPEDE-2089] Create accessibility page for picker

---

src/documentation/pages/components/forms/file-input/_accessibility.vue

https://ctl.atlassian.net/browse/DPEDE-1969

[DPEDE-1969] Create accessibility page for file input

---

src/documentation/pages/components-wip/tabs/_properties.vue
src/website/views/components/tabs/_properties.pug

https://ctl.atlassian.net/browse/DPEDE-2374

[DPEDE-2374] Add TabTrigger interface in Tabs properties doc

---

src/custom-elements/src/components/number-input/number-input.tsx

Events tested on native input with type number: 
Comparison of the events -> the chiEvents are from our number-input-wc, and lowercase events are from native element. Scenarios and events: 
Clicking arrow up or down when the value is not at max or min, and then clicking outside of the element to get blur. 
Just click on the element and out of element:
Clicking element, deleting the value(backspace once), entering value with keyboard (one digit) and clicking out of the element: 
Clicking on arrow up when max value is set (we see only focus, number of clicks and blur)

[DPEDE-2380] Fixed and adjusted number inputs events: chiChange, chiClick, chiFocus

---

src/custom-elements/src/components/tabs/tabs.tsx
src/custom-elements/src/utils/Compare.ts

[DPEDE-2391] Fix dynamic adding and deleting tabs

---

src/chi/components/input-number/_input.scss
src/custom-elements/src/components/number-input/number-input.scss

https://lumen.atlassian.net/browse/DPEDE-2528

[DPEDE-2528] Fix focus on number input out of this

---

CHANGELOG.md
package.json
src/boilerplates/stencil/chi-stencil-boilerplate/src/index.html
src/documentation/constants/configs.ts
src/documentation/constants/constants.ts
src/website/assets/scripts/globalConfigs.js
src/website/layouts/default.pug
src/website/layouts/partials/header.pug
src/website/layouts/partials/sriDoc.pug
src/website/layouts/partials/titlebar.pug
src/website/views/components/button/_accessibility.pug
src/website/views/components/date-picker/_accessibility.pug
src/website/views/components/forms/checkbox/_accessibility.pug
src/website/views/components/forms/number-input/_accessibility.pug
src/website/views/components/forms/radio-button/_accessibility.pug
src/website/views/components/forms/select/_accessibility.pug
src/website/views/components/forms/text-input/_accessibility.pug
src/website/views/components/forms/textarea/_accessibility.pug
src/website/views/components/forms/toggle-switch/_accessibility.pug
src/website/views/components/link/_accessibility.pug
src/website/views/components/phone-input/_accessibility.pug
src/website/views/components/picker-group/_accessibility.pug
src/website/views/components/picker/_accessibility.pug
src/website/views/components/time-picker/_accessibility.pug
src/website/views/getting-started/installation.pug
src/website/views/getting-started/whats-new.pug

https://lumen.atlassian.net/browse/DPEDE-2713

[DPEDE-2713] Prepare Chi 6.7.0 release

---

CHANGELOG.md
package.json
src/boilerplates/stencil/chi-stencil-boilerplate/src/index.html
src/documentation/constants/configs.ts
src/documentation/constants/constants.ts
src/website/assets/scripts/globalConfigs.js
src/website/layouts/default.pug
src/website/layouts/partials/header.pug
src/website/layouts/partials/sriDoc.pug
src/website/layouts/partials/titlebar.pug
src/website/views/components/button/_accessibility.pug
src/website/views/components/date-picker/_accessibility.pug
src/website/views/components/forms/checkbox/_accessibility.pug
src/website/views/components/forms/number-input/_accessibility.pug
src/website/views/components/forms/radio-button/_accessibility.pug
src/website/views/components/forms/select/_accessibility.pug
src/website/views/components/forms/text-input/_accessibility.pug
src/website/views/components/forms/textarea/_accessibility.pug
src/website/views/components/forms/toggle-switch/_accessibility.pug
src/website/views/components/link/_accessibility.pug
src/website/views/components/phone-input/_accessibility.pug
src/website/views/components/picker-group/_accessibility.pug
src/website/views/components/picker/_accessibility.pug
src/website/views/components/time-picker/_accessibility.pug
src/website/views/getting-started/installation.pug
src/website/views/getting-started/whats-new.pug

https://lumen.atlassian.net/browse/DPEDE-2728

[DPEDE-2728] Prepare Chi 6.8.0 release

---

CHANGELOG.md
package.json
src/boilerplates/stencil/chi-stencil-boilerplate/src/index.html
src/documentation/constants/configs.ts
src/documentation/constants/constants.ts
src/website/assets/scripts/globalConfigs.js
src/website/layouts/default.pug
src/website/layouts/partials/header.pug
src/website/layouts/partials/sriDoc.pug
src/website/layouts/partials/titlebar.pug
src/website/views/components/button/_accessibility.pug
src/website/views/components/date-picker/_accessibility.pug
src/website/views/components/forms/checkbox/_accessibility.pug
src/website/views/components/forms/number-input/_accessibility.pug
src/website/views/components/forms/radio-button/_accessibility.pug
src/website/views/components/forms/select/_accessibility.pug
src/website/views/components/forms/text-input/_accessibility.pug
src/website/views/components/forms/textarea/_accessibility.pug
src/website/views/components/forms/toggle-switch/_accessibility.pug
src/website/views/components/link/_accessibility.pug
src/website/views/components/phone-input/_accessibility.pug
src/website/views/components/picker-group/_accessibility.pug
src/website/views/components/picker/_accessibility.pug
src/website/views/components/time-picker/_accessibility.pug
src/website/views/getting-started/installation.pug
src/website/views/getting-started/whats-new.pug

https://lumen.atlassian.net/browse/DPEDE-2792

[DPEDE-2792] Prepare Chi 6.10.0 release

---

CHANGELOG.md
package.json
src/boilerplates/stencil/chi-stencil-boilerplate/src/index.html
src/documentation/constants/configs.ts
src/documentation/constants/constants.ts
src/website/assets/scripts/globalConfigs.js
src/website/layouts/default.pug
src/website/layouts/partials/header.pug
src/website/layouts/partials/sriDoc.pug
src/website/layouts/partials/titlebar.pug
src/website/views/components/button/_accessibility.pug
src/website/views/components/date-picker/_accessibility.pug
src/website/views/components/forms/checkbox/_accessibility.pug
src/website/views/components/forms/number-input/_accessibility.pug
src/website/views/components/forms/radio-button/_accessibility.pug
src/website/views/components/forms/select/_accessibility.pug
src/website/views/components/forms/text-input/_accessibility.pug
src/website/views/components/forms/textarea/_accessibility.pug
src/website/views/components/forms/toggle-switch/_accessibility.pug
src/website/views/components/link/_accessibility.pug
src/website/views/components/phone-input/_accessibility.pug
src/website/views/components/picker-group/_accessibility.pug
src/website/views/components/picker/_accessibility.pug
src/website/views/components/time-picker/_accessibility.pug
src/website/views/getting-started/installation.pug
src/website/views/getting-started/whats-new.pug

https://lumen.atlassian.net/browse/DPEDE-2822

[DPEDE-2822] Prepare Chi 6.12.0 release

---

CHANGELOG.md
package.json
src/boilerplates/stencil/chi-stencil-boilerplate/src/index.html
src/documentation/constants/configs.ts
src/documentation/constants/constants.ts
src/website/assets/scripts/globalConfigs.js
src/website/layouts/default.pug
src/website/layouts/partials/header.pug
src/website/layouts/partials/sriDoc.pug
src/website/layouts/partials/titlebar.pug
src/website/views/components/button/_accessibility.pug
src/website/views/components/date-picker/_accessibility.pug
src/website/views/components/forms/checkbox/_accessibility.pug
src/website/views/components/forms/number-input/_accessibility.pug
src/website/views/components/forms/radio-button/_accessibility.pug
src/website/views/components/forms/select/_accessibility.pug
src/website/views/components/forms/text-input/_accessibility.pug
src/website/views/components/forms/textarea/_accessibility.pug
src/website/views/components/forms/toggle-switch/_accessibility.pug
src/website/views/components/link/_accessibility.pug
src/website/views/components/phone-input/_accessibility.pug
src/website/views/components/picker-group/_accessibility.pug
src/website/views/components/picker/_accessibility.pug
src/website/views/components/time-picker/_accessibility.pug
src/website/views/getting-started/installation.pug
src/website/views/getting-started/whats-new.pug

https://lumen.atlassian.net/browse/DPEDE-2896

[DPEDE-2896] Prepare Chi 6.13.0 release

---

CHANGELOG.md
package.json
src/boilerplates/stencil/chi-stencil-boilerplate/src/index.html
src/documentation/constants/configs.ts
src/documentation/constants/constants.ts
src/website/assets/scripts/globalConfigs.js
src/website/layouts/default.pug
src/website/layouts/partials/header.pug
src/website/layouts/partials/sriDoc.pug
src/website/layouts/partials/titlebar.pug
src/website/views/components/button/_accessibility.pug
src/website/views/components/date-picker/_accessibility.pug
src/website/views/components/forms/checkbox/_accessibility.pug
src/website/views/components/forms/number-input/_accessibility.pug
src/website/views/components/forms/radio-button/_accessibility.pug
src/website/views/components/forms/select/_accessibility.pug
src/website/views/components/forms/text-input/_accessibility.pug
src/website/views/components/forms/textarea/_accessibility.pug
src/website/views/components/forms/toggle-switch/_accessibility.pug
src/website/views/components/link/_accessibility.pug
src/website/views/components/phone-input/_accessibility.pug
src/website/views/components/picker-group/_accessibility.pug
src/website/views/components/picker/_accessibility.pug
src/website/views/components/time-picker/_accessibility.pug
src/website/views/getting-started/installation.pug
src/website/views/getting-started/whats-new.pug

https://lumen.atlassian.net/browse/DPEDE-2936

[DPEDE-2936] Prepare Chi 6.15.0 release

---

CHANGELOG.md
package.json
src/boilerplates/stencil/chi-stencil-boilerplate/src/index.html
src/documentation/constants/configs.ts
src/documentation/constants/constants.ts
src/website/assets/scripts/globalConfigs.js
src/website/layouts/default.pug
src/website/layouts/partials/header.pug
src/website/layouts/partials/sriDoc.pug
src/website/layouts/partials/titlebar.pug
src/website/views/components/button/_accessibility.pug
src/website/views/components/date-picker/_accessibility.pug
src/website/views/components/forms/checkbox/_accessibility.pug
src/website/views/components/forms/number-input/_accessibility.pug
src/website/views/components/forms/radio-button/_accessibility.pug
src/website/views/components/forms/select/_accessibility.pug
src/website/views/components/forms/text-input/_accessibility.pug
src/website/views/components/forms/textarea/_accessibility.pug
src/website/views/components/forms/toggle-switch/_accessibility.pug
src/website/views/components/link/_accessibility.pug
src/website/views/components/phone-input/_accessibility.pug
src/website/views/components/picker-group/_accessibility.pug
src/website/views/components/picker/_accessibility.pug
src/website/views/components/time-picker/_accessibility.pug
src/website/views/getting-started/installation.pug
src/website/views/getting-started/whats-new.pug

https://lumen.atlassian.net/browse/DPEDE-3028

[DPEDE-3028] Prepare Chi 6.16.0 release

---

src/chi/components/modal/modal.scss

https://lumen.atlassian.net/browse/DPEDE-3210

[DPEDE-3210] Improve icon close modal scss

---

CHANGELOG.md
cicd/jenkins/Jenkinsfile
package.json
src/boilerplates/stencil/chi-stencil-boilerplate/src/index.html
src/documentation/constants/configs.ts
src/documentation/constants/constants.ts
src/website/assets/scripts/globalConfigs.js
src/website/layouts/default.pug
src/website/layouts/partials/header.pug
src/website/layouts/partials/sriDoc.pug
src/website/layouts/partials/titlebar.pug
src/website/views/components/button/_accessibility.pug
src/website/views/components/date-picker/_accessibility.pug
src/website/views/components/forms/checkbox/_accessibility.pug
src/website/views/components/forms/number-input/_accessibility.pug
src/website/views/components/forms/radio-button/_accessibility.pug
src/website/views/components/forms/select/_accessibility.pug
src/website/views/components/forms/text-input/_accessibility.pug
src/website/views/components/forms/textarea/_accessibility.pug
src/website/views/components/forms/toggle-switch/_accessibility.pug
src/website/views/components/link/_accessibility.pug
src/website/views/components/phone-input/_accessibility.pug
src/website/views/components/picker-group/_accessibility.pug
src/website/views/components/picker/_accessibility.pug
src/website/views/components/time-picker/_accessibility.pug
src/website/views/getting-started/installation.pug
src/website/views/getting-started/whats-new.pug

https://lumen.atlassian.net/browse/DPEDE-3254

[DPEDE-3254] Prepare Chi 6.22.0 release

---

Dockerfile
cicd/jenkins/Jenkinsfile

https://lumen.atlassian.net/browse/DPEDE-3302

[DPEDE-3302] Fix cookie dependency in master

---

lib/chi-vue/index.umd.js

Update Chi Vue UMD to latest version

[DPEDE-2106] Include new chi-vue umd version

---

src/chi/templates/app-layout.scss

https://lumen.atlassian.net/browse/DPEDE-3534

[DPEDE-3534] Add chi-main__wrapper class

---

backstop-non-responsive-ce.json
backstop-non-responsive.json
backstop-responsive.json
cicd/nginx/default.conf
package-lock.json
package.json
scripts/build/build.sh
scripts/build/js/build.js
sri.json

https://lumen.atlassian.net/browse/DPEDE-3813

[DPEDE-3813] Prepare 6.35.0 release

---

package-lock.json
package.json

[DPEDE-2106] Update documentation version to 1.7.0

---

backstop-non-responsive-ce.json
backstop-non-responsive.json
backstop-responsive.json
cicd/nginx/default.conf
package-lock.json
package.json
sri.json

https://lumen.atlassian.net/browse/DPEDE-3902

[DPEDE-3902] Prepare Chi 6.36.0 release

---

package-lock.json
package.json

[DPEDE-2106] Update documentation version to 1.8.1

---

package-lock.json
package.json

[DPEDE-2106] Update documentation version to 1.9.0

---

backstop-non-responsive-ce.json
backstop-non-responsive.json
backstop-responsive.json
cicd/nginx/default.conf
package-lock.json
package.json

https://lumen.atlassian.net/browse/DPEDE-3986

[DPEDE-3986] Prepare Chi release 6.38.0

---

package-lock.json
package.json

[DPEDE-2106] Update documentation version to 1.9.1

---

backstop-non-responsive-ce.json
backstop-non-responsive.json
backstop-responsive.json
cicd/nginx/default.conf
package-lock.json
package.json

https://lumen.atlassian.net/browse/DPEDE-4020

[DPEDE-4020] Prepare chi 6.38.1 release

---

package-lock.json
package.json

[DPEDE-2106] Update documentation version to 1.10.0

---

backstop-non-responsive-ce.json
backstop-non-responsive.json
backstop-responsive.json
cicd/nginx/default.conf
package-lock.json
package.json

https://lumen.atlassian.net/browse/DPEDE-4036

[DPEDE-4036] Prepare chi 6.39.0 release

---

package-lock.json
package.json

Update Chi Vue to latest version

[DPEDE-2106] Include new chi-vue version

---

package-lock.json
package.json

[DPEDE-2106] Update documentation version to 1.11.0

---

package-lock.json
package.json

[DPEDE-2106] Update documentation version to 1.12.0

---

backstop-non-responsive-ce.json
backstop-non-responsive.json
backstop-responsive.json
cicd/nginx/default.conf
package-lock.json
package.json

https://lumen.atlassian.net/browse/DPEDE-4049

[DPEDE-4049] Prepare chi 6.41.0 release

---

package-lock.json
package.json

Update Chi CE to latest version

[DPEDE-2106] Include new chi custom elements version

---

package-lock.json
package.json
scripts/build/build.sh
sri.json

https://lumen.atlassian.net/browse/DPEDE-4122

[DPEDE-4122] Copy docs json from custom elements build to dist

---

package-lock.json
package.json

[DPEDE-2106] Update documentation version to 1.13.0

---

package-lock.json
package.json

[DPEDE-2106] Update documentation version to 1.14.0

---

package-lock.json
package.json

[DPEDE-2106] Update documentation version to 1.18.0

---

scripts/build/build.sh
scripts/build/css/build.js
scripts/chi.cjs
scripts/serve/serve.cjs
sri.json

Potential fix for: 
[https://github.com/CenturyLink/Chi/security/code-scanning/18](https://github.com/CenturyLink/Chi/security/code-scanning/18)
[https://github.com/CenturyLink/Chi/security/code-scanning/17](https://github.com/CenturyLink/Chi/security/code-scanning/17)
[https://github.com/CenturyLink/Chi/security/code-scanning/144](https://github.com/CenturyLink/Chi/security/code-scanning/144)
[https://github.com/CenturyLink/Chi/security/code-scanning/143](https://github.com/CenturyLink/Chi/security/code-scanning/143)
[https://github.com/CenturyLink/Chi/security/code-scanning/142](https://github.com/CenturyLink/Chi/security/code-scanning/142)
[https://github.com/CenturyLink/Chi/security/code-scanning/28](https://github.com/CenturyLink/Chi/security/code-scanning/28)
This pull request …

[DPEDE-2106] Fix Code Scanning alerts

---

package-lock.json
package.json

[DPEDE-2106] Update documentation version to 1.20.0

---

package-lock.json
package.json

[DPEDE-2106] Update documentation version to 1.21.0

---

backstop-non-responsive-ce.json
backstop-non-responsive.json
backstop-responsive.json
cicd/nginx/default.conf
package-lock.json
package.json
sri.json

https://lumen.atlassian.net/browse/DPEDE-4510

[DPEDE-4510] Prepare Chi 6.49.0 release

---

backstop-non-responsive-ce.json
backstop-non-responsive.json
backstop-responsive.json
cicd/nginx/default.conf
package-lock.json
package.json
sri.json

https://lumen.atlassian.net/browse/DPEDE-4525

[DPEDE-4525] Prepare chi 6.50.0 release

---

backstop-non-responsive-ce.json
backstop-non-responsive.json
backstop-responsive.json
cicd/nginx/default.conf
package-lock.json
package.json
sri.json

https://lumen.atlassian.net/browse/DPEDE-4560

[DPEDE-4560] Prepare chi 6.51.0 release

---

backstop-non-responsive-ce.json
backstop-non-responsive.json
backstop-responsive.json
cicd/nginx/default.conf
package-lock.json
package.json
sri.json

https://lumen.atlassian.net/browse/DPEDE-4590

[DPEDE-4590] Prepare chi 6.52.0 release

---

backstop-non-responsive-ce.json
backstop-non-responsive.json
backstop-responsive.json
cicd/nginx/default.conf
package-lock.json
package.json
sri.json

https://lumen.atlassian.net/browse/DPEDE-4667

[DPEDE-4667] Prepare Chi 6.54.0 release

---

backstop-non-responsive-ce.json
backstop-non-responsive.json
backstop-responsive.json
cicd/nginx/default.conf
package-lock.json
package.json
sri.json

https://lumen.atlassian.net/browse/DPEDE-4667

[DPEDE-4667] Prepare Chi 6.55.0 release

---

package-lock.json
package.json

[DPEDE-2106] Update documentation version to 1.28.0

---

package-lock.json
package.json

[DPEDE-2106] Update documentation version to 1.29.0

---

backstop-non-responsive-ce.json
backstop-non-responsive.json
backstop-responsive.json
cicd/nginx/default.conf
package-lock.json
package.json
sri.json

https://lumen.atlassian.net/browse/DPEDE-4837

[DPEDE-4837] Prepare chi 6.59.0 release

---

package-lock.json
package.json

[DPEDE-2106] Update documentation version to 1.33.0

---

package-lock.json
package.json

[DPEDE-2106] Update documentation version to 1.35.0

---

index.html
src/chi/javascript/components/app-layout.js
src/chi/javascript/components/global-nav.js
src/chi/javascript/index.js
sri.json

https://lumen.atlassian.net/browse/DPEDE-4964
This pull request refactors the HTML structure in `index.html` to improve readability and maintainability, primarily by flattening nested elements, reformatting multi-line content, and enhancing code consistency. The changes do not affect functionality but make the markup cleaner and easier to work with.
**Markup simplification and consistency:**
* Flattened nested `<div>` and other elements throughout the dashboard sections, such as headers, cards, and contact items, by removing unnecessary line breaks and indentation. This improves code readability and reduces visual clutter. [[1]](diffhunk://#diff-0eb547304658805aad788d320f10bf1f292797b5e6d745a3bf617584da017051L273-R294) [[2]](diffhunk://#diff-0eb547304658805aad788d320f10bf1f292797b5e6d745a3 …

[DPEDE-4964] Make sidenav collapsable in 1440 viewport size

---

package-lock.json
package.json

[DPEDE-2106] Update documentation version to 1.36.0

---

backstop-non-responsive-ce.json
backstop-non-responsive.json
backstop-responsive.json
cicd/nginx/default.conf
package-lock.json
package.json
sri.json

https://lumen.atlassian.net/browse/DPEDE-4969

[DPEDE-4969] Prepare Chi 6.64.0 release
